version: '3.8'

services:
  nextjs-crud:
    image: node:18.16.1
    container_name: nextjs-crud
    restart: unless-stopped
    ports:
      - 4000:3000
    user: node
    environment:
      TZ: America/Guayaquil
      NODE_ENV: development
    volumes:
      - ./:/home/node/app
    working_dir: /home/node/app
    networks:
      - default
    command: tail -f /dev/null

networks:
  default:
    external: true
    name: docker
