import {Inter} from 'next/font/google';
import './globals.css';
import {TasksProvider} from '@/context/TasksContext';
import Navbar from '@/components/Navbar';
import {Toaster} from './Toaster';

const inter = Inter({subsets: ['latin']})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({children}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <TasksProvider>
          <Navbar />
          {children}
          <Toaster />
        </TasksProvider>
      </body>
    </html>
  )
}
